godspeedsystems/gs-node-service

- package.json
Resolves prisma client conflict on godspeed build.
> udpated ts package version

- src/core/validation/event.schema.json
Reverts godspeedsystems/gs-node-service#609
> Revert "fix: allowed authn in event to accepts string as well"

- src/http_listener.ts
bodyParser Json called twice - refactored
> invalid payload issue - minor fix

- src/core/functionLoader.ts
- src/core/interfaces.ts
Resolved com gs return behavior in parallel and in other built-in functions
> resolved com gs return issue

- src/core/codeLoader.ts
- src/core/datasourceLoader.ts
- src/core/yamlLoader.ts
modified path in glob function to work in windows(codeLoader,datasourceLoader,yamlLoader)
> chore: changed path in glob to work in windows

- src/redis/index.ts
example config for redis datasource.
```yaml
type: redis
url: redis://default:igfOuioeA3f11kBqQU2GC8W1ZuhIqtAh@redis-18990.c1.asia-northeast1-1.gce.cloud.redislabs.com:18990
cluster:
useReplicas: true
rootNodes:
- url: redis://@redis-node-0:6379
- url: redis://@redis-node-1:6379
- url: redis://@redis-node-2:6379
- url: redis://@redis-node-3:6379
- url: redis://@redis-node-4:6379
- url: redis://@redis-node-5:6379
defaults:
socket:
connectTimeout: 5000
username: default
password: bitnami
```
> enabled clustering mode for redis

- .vscode/settings.json
- package-lock.json
- package.json
- src/api-specs/api-spec.ts
- src/core/functionLoader.ts
- src/core/interfaces.ts
- src/core/script.ts
- src/core/sourcemap.ts
- src/core/transpiler.ts
- tsconfig.json
1. After project yaml changes need to run `godspeed build`
2. Now we are allowing js/ts function to become event handler
```
export default function main(ctx) {
....
ctx.outputs['main'] = {
success: true,
code: 200, 
data: 'Hello World'
}
}
main.id = 'main'
```
> Adding debugger support

- src/core/functionLoader.ts
- src/core/interfaces.ts
- src/core/utils.ts
As per issue #843 and #844
First @xCodeMuse @siddarthvader and @gurjotkaur20 please review the changes.
I am requesting all three of you to review so that we are all updated and in sync, more and more on the core code.
Thereafter please test with all test cases whether passing or not.
> 843 add json types in function loader

- .github/workflows/v2.yml
Implements Integration Tests as per #752
> feat: added CI to run Integration Tests:

- src/app.ts
- src/aws/index.ts
- src/core/authnWorkflow.ts
- src/core/eventLoader.ts
- src/core/expandVariables.ts
- src/core/interfaces.ts
- src/core/jsonSchemaValidation.ts
- src/core/utils.ts
- src/functions/com/gs/http.ts
- src/functions/com/gs/kafka.ts
- src/functions/com/gs/soap.ts
- src/scriptRuntime.ts
- src/tests/fixtures/GSParallelFunction/functions/com/gs/http.ts
- src/tests/fixtures/GSSeriesFunction/functions/com/gs/http.ts
- src/tests/fixtures/loadFunctions/functions/com/gs/http.ts
- src/tests/fixtures/loadModules/functions/com/gs/http.ts
- src/tests/fixtures/onErrorFalse/functions/com/gs/http.ts
Commented unwated logs for now.
- Remove the framework level logs.
- Dont change the loading logs.
> Remove Unwanted Framework Log

- src/app.ts
- src/core/utils.ts
- src/core/yamlLoader.ts
Event validation on loadtime throw a proper error message with the file name for easy debugging.
Cases covered:
- Invalid Client [tested]
- Fn not present [tested]
- Invalid Fn in case no function exist in the functions [tested]
- Validate Tasks of the workflow with workflow name [tested]
- ID of the workflow [NOT YET, TO BE DISCUSSED]
> Throw proper errors messages for event on loadtime with filename

- src/core/codeLoader.ts
- src/core/interfaces.ts
- src/core/scriptRuntime.ts
- src/godspeed.ts
> added plugin feature like v1

- src/core/logger.ts
[Issue](https://github.com/godspeedsystems/gs-node-service/issues/887)
> server crash: fix logger by overriding and catching error in logger.ts file

- src/core/expandVariables.ts
- src/godspeed.ts
> Fix mappings loading issue in events

- src/core/expandVariables.ts
- src/godspeed.ts
Reverts godspeedsystems/gs-node-service#936
> Revert: Fix mappings loading issue in events

- src/core/utils.ts
[Issue](https://github.com/godspeedsystems/gs-node-service/issues/948)
> Change Default Scripting Language

- package.json
- src/core/datasourceLoader.ts
- src/core/interfaces.ts
- src/core/jsonSchemaValidation.ts
- src/godspeed.ts
> more changs

- src/core/datasourceLoader.ts
- src/core/eventsourceLoader.ts
- src/godspeed.ts
> feature/954: Now workflows can be invoked without event source

- src/core/interfaces.ts
- src/core/jsonSchemaValidation.ts
- src/godspeed.ts
- src/router/swagger.ts
linked to #971 generate swagger specs
> Features/971 swagger UI gen

- src/core/functionLoader.ts
> removed unncessary loop and validating datasource in task as fn after evaluating fn script

- package.json
- src/core/eventLoader.ts
- src/core/yamlLoader.ts
- src/godspeed.ts
- src/router/swagger.ts
#990 
In godspeed-cli linked to [this issue](https://github.com/godspeedsystems/godspeed-cli/pull/77)
In api-generator linked to [this issue](https://github.com/godspeedsystems/gs-api-generator/pull/19)
> feat: 990 schema enhancements

- src/functions/com/gs/transform.ts
> fix: updated com.gs.transform

- src/godspeed.ts
> fix: remove otel package initialization from gs-node-service

- src/godspeed.ts
Check if _previewFeatures exists
> fix: add ? to check if existing

- src/godspeed.ts
> fix: validation_error renamed to validationError

- package.json
- src/logger/logger.ts
> 739_updated_logger.ts to prevent crashing

- src/core/caching.ts
- src/core/interfaces.ts
> fix: refactor caching methods
